package com.t7solution.databaseCrud.model;

import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;

@Entity // mark this class as a JPA Entity, which will be mapped to a table in the PostgreSQL database
public class Student {

    @Id // defines primary key field(id). which will be autogenerated using @GeneratedValue with identity strategy
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private int id;

    //Fields: The student has name, email.
    private String name;
    private String email;

//    public Student(int id, String name, String email) {
//        this.id = id;
//        this.name = name;
//        this.email = email;
//    }

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }
}
